import orjson
import hashlib
import hmac
from typing import Dict, Tuple
import base64

from src.exchanges.common.client import Client


class BitgetClient(Client):
    recv_window = 1000

    errors: Dict[int, Tuple[bool, str]] = {    
        0000: (False, "success!"),
        40001: (False, "ACCESS_KEY cannot be empty"),
        40002: (False, "ACCESS_SIGN cannot be empty"),
        40003: (False, "Signature cannot be empty"),
        40004: (False, "Request timestamp expired"),
        40005: (False, "Invalid ACCESS_TIMESTAMP"),
        40006: (False, "Invalid ACCESS_KEY"),
        40007: (False, "Invalid Content_Type"),
        40008: (False, "Request timestamp expired"),
        40009: (False, "Sign signature error"),
        40010: (True, "Request timed out"),
        40011: (False, "ACCESS_PASSPHRASE cannot be empty"),
        40012: (False, "API key/password is incorrect"),
        40013: (False, "User status is abnormal"),
        40014: (False, "Incorrect permissions, need {0} permissions"),
        40015: (True, "System is abnormal, please try again later"),
        40016: (False, "The user must bind the phone or Google"),
        40017: (False, "Parameter verification failed {0}"),
        40018: (False, "Invalid IP"),
        40019: (False, "Parameter {0} cannot be empty"),
        40020: (False, "Parameter {0} error"),
        40021: (False, "User disabled withdrawal"),
        40022: (False, "The business of this account has been restricted"),
        40023: (False, "The business of this account has been restricted"),
        40024: (False, "Account has been frozen"),
        40025: (False, "The business of this account has been restricted"),
        40026: (False, "User is disabled"),
        40027: (False, "Withdrawals in this account area must be KYC"),
        40028: (False, "This subUid does not belong to this account"),
        40029: (False, "This account is not a Broker, please apply to become a Broker first"),
        40031: (False, "The account has been cancelled and cannot be used again"),
        40032: (False, "The max of sub-accounts created has reached the limit"),
        40033: (False, "This email has been bound"),
        40034: (False, "Parameter {0} does not exist"),
        40035: (False, "Judging from your login information, you are required to complete KYC first for compliance reasons."),
        40036: (False, "Passphrase is incorrect"),
        40037: (False, "API key does not exist"),
        40038: (False, "The current IP is not in the API key IP whitelist"),
        40039: (False, "FD Broker's user signature error"),
        40040: (False, "User API key permission setting error"),
        40041: (False, "User's API key does not exist"),
        40043: (False, "FD Broker does not exist"),
        40045: (False, "The bound user cannot be an FD broker"),
        40047: (False, "FD Broker binding related interface call frequency limit"),
        40048: (False, "The user's API key must be the parent account"),
        40049: (False, "User-related fields decrypt error"),
        40051: (False, "This account is not an FD Broker, please apply to become an FD Broker first"),
        40052: (False, "Security settings have been modified for this account. For the safety of your account, withdrawals are prohibited within 24 hours"),
        40053: (False, "Value range verification failed: {0} should be between {1}"),
        40054: (False, "The data fetched by {0} is empty"),
        40055: (False, "SubName must be an English letter with a length of 8"),
        40056: (False, "Remark must be length of 1 ~ 20"),
        40057: (False, "Parameter {0} {1} does not meet specification"),
        40058: (False, "Parameter {0} Only a maximum of {1} is allowed"),
        40059: (False, "Parameter {0} should be less than {1}"),
        40060: (False, "SubNames already exist"),
        40061: (False, "Sub-account not allowed access"),
        40063: (False, "API exceeds the maximum limit added"),
        40064: (False, "Sub-account creation failed, please check if there is a duplicate"),
        40065: (False, "This sub API key does not exist"),
        40066: (False, "This subUid does not belong to the account or is not a virtual sub-account"),
        40067: (False, "Sub-account creation failed, please check if there is a duplicate"),
        40068: (False, "Disable subaccount access"),
        40069: (False, "The maximum number of sub-accounts created has been reached"),
        40070: (False, "Passphrase 8-32 characters with letters and numbers"),
        40071: (False, "SubName exists duplication"),
        40072: (False, "Symbol {0} is invalid or not supported for mix contract trade"),
        40074: (False, "{0} MatchRunServer does not exist"),
        40078: (False, "Timestamp for this request is outside of the ME receiveWindow."),
        40079: (False, "ReceiveWindow timestamp must be less than 60s"),
        40100: (False, "Due to regulatory requirements, Hong Kong IPs are required to complete identity verification first"),
        40101: (False, "Please complete KYC"),
        40102: (False, "Symbol does not exist"),
        40104: (False, "Based on your IP address, it appears that you are located in a country or region where we are currently unable to provide services"),
        40109: (False, "The data of the order cannot be found, please confirm the order number"),
        40172: (False, "Parameter error"),
        40199: (False, "Traders are prohibited from calling the API"),
        40200: (True, "Server upgrade, please try again later"),
        40301: (False, "Permission has not been obtained yet. If you need to use it, please contact customer service"),
        40303: (False, "Can only query up to 20,000 data"),
        40304: (False, "clientOid or clientOrderId length cannot be greater than 50"),
        40305: (False, "clientOid or clientOrderId length cannot be greater than 64, and cannot be Martian characters"),
        40306: (False, "Batch processing orders can only process up to 20"),
        40308: (False, "The contract is being temporarily maintained"),
        40309: (False, "The contract has been removed"),
        40400: (False, "Status check abnormal"),
        40401: (False, "The operation cannot be performed"),
        40402: (False, "orderId or clientOid format error"),
        40407: (False, "The query direction is not the direction entrusted by the plan"),
        40408: (False, "Range error"),
        40409: (False, "Wrong format"),
        40404: (False, "Request URL NOT FOUND"),
        40704: (False, "Can only check the data of the last three months"),
        40705: (False, "The start and end time cannot exceed 90 days"),
        40706: (False, "Wrong order price"),
        40707: (False, "Start time is greater than end time"),
        40708: (False, "client_oid duplicate"),
        40709: (False, "There is no position in this position, and no automatic margin call can be set"),
        40710: (False, "Abnormal account status"),
        40711: (False, "Insufficient contract account balance"),
        40712: (False, "Insufficient margin"),
        40713: (False, "Cannot exceed the maximum transferable margin amount"),
        40714: (False, "No direct margin call is allowed"),
        40715: (False, "Delegate count cannot exceed max of open count"),
        40716: (False, "This trading pair does not support Cross Margin mode"),
        40717: (False, "The number of closed positions cannot exceed the number of sheets held"),
        40718: (False, "The entrusted price of closing long positions shall not be lower than the liquidation price"),
        40719: (False, "The entrusted price of closing short positions is not allowed to be higher than the liquidation price"),
        40720: (False, "Swap hand depth does not exist"),
        40721: (False, "Market price list is not allowed at present"),
        40722: (True, "Due to excessive price fluctuations and the insufficient market price entrusted cost, the opening commission failed."),
        40723: (False, "The total number of unexecuted orders is too high"),
        40724: (False, "Parameter is empty"),
        40725: (False, "Service returned an error"),
        40726: (False, "Cross margin does not support Auto Margin Replenishment (AMR)"),
        40727: (False, "Cross margin does not support margin adjustment"),
        40728: (False, "You're logged in as trader, please close position for current copy trade orders"),
        40729: (False, "Failed to adjust the position, the current position or order or plan order"),
        40730: (False, "There is currently a commission or a planned commission, and the leverage cannot be adjusted"),
        40731: (False, "This product does not support copy trading"),
        40732: (False, "Not currently a trader"),
        40733: (False, "The order closing has been processed"),
        40734: (False, "Failed to place an order, the minimum number of traders to open a position {0}"),
        40735: (False, "Long position take profit price should be greater than the average opening price"),
        40736: (False, "Long position take profit price is greater than the current price"),
        40737: (False, "The short position take profit price should be less than the average opening price"),
        40738: (False, "The short position take profit price should be less than the current price"),
        40739: (False, "The stop loss price of a long position should be less than the average opening price"),
        40740: (False, "The stop loss price of a long position should be less than the current price"),
        40741: (False, "The stop loss price of a short position should be greater than the average opening price"),
        40742: (False, "The stop loss price of the short position should be greater than the current price"),
        40743: (False, "The order is being closed and cannot be closed again"),
        40744: (False, "The tracking order status is wrong"),
        40745: (False, "This order is being commissioned, and liquidation is not supported temporarily"),
        40746: (False, "The current maximum number of positions that can be closed is {0}, if you exceed the number, please go to the current order to close the position"),
        40747: (False, "The bonus is not allowed to hold two-way positions"),
        40748: (False, "The commission price is higher than the highest bid price"),
        40749: (False, "The commission price is lower than the lowest selling price"),
        40750: (False, "The plan commission for this contract has reached the upper limit"),
        40751: (False, "The contract's stop profit and stop loss order has reached the upper limit"),
        40752: (False, "You are disabled for current business, if you have any questions, please contact customer service"),
        40753: (False, "The contract transaction business is disabled, if you have any questions, please contact customer service"),
        40754: (False, "Balance not enough"),
        40755: (False, "Not enough open positions are available."),
        40756: (False, "The balance lock is insufficient."),
        40757: (False, "Not enough position is available."),
        40758: (False, "The position lock is insufficient."),
        40759: (False, "No assets"),
        40760: (False, "Account abnormal status"),
        40761: (False, "The total number of unfilled orders is too high"),
        40762: (False, "The order size is greater than the max open size"),
        40763: (False, "The number of orders cannot exceed the maximum amount of the corresponding gear"),
        40764: (False, "The remaining amount of the order is less than the current transaction volume"),
        40765: (False, "The remaining volume of the position is less than the current transaction volume"),
        40766: (False, "The number of open orders is less than this transaction volume"),
        40767: (False, "Position does not exist when opening a position"),
        40768: (False, "Order does not exist"),
        40769: (False, "Reject order has been completed"),
        40770: (False, "The settlement or fee currency configuration was not found."),
        40771: (False, "When there is a gap, you cannot have a position closing order."),
        40772: (False, "The account does not exist"),
        40773: (False, "Closed positions can only occur in two-way positions."),
        40774: (False, "The order type for unilateral position must also be the unilateral position type."),
        40775: (False, "The market-making account can only be a unilateral position type."),
        40776: (False, "Error creating order."),
        40777: (False, "Cancel order error."),
        40778: (False, "Coin pair {0} does not support {1} currency as margin"),
        40779: (False, "Please check that the correct delegateType is used"),
        40780: (False, "There are multiple risk handling records for the same symbolId at the same time"),
        40781: (False, "The transfer order was not found"),
        40782: (False, "Internal transfer error"),
        40783: (False, "No gear found"),
        40784: (False, "Need to configure modify depth account"),
        40785: (False, "Need to configure draw line account"),
        40786: (False, "Duplicate clientOid"),
        40787: (False, "The price step does not match"),
        40788: (False, "Internal batch transfer error"),
        40789: (False, "The tokenId is duplicated in the configuration item"),
        40790: (False, "Duplicate symbolCode in configuration item"),
        40791: (False, "The baseToken or quoteToken of symbolCode does not exist"),
        40792: (False, "The symbol in the configuration item is duplicated"),
        40793: (False, "The symbolCode of BusinessSymbol does not exist"),
        40794: (False, "The supportMarginToken of BusinessSymbol is not configured"),
        40795: (False, "The transaction is suspended due to settlement or maintenance reasons"),
        40796: (False, "The adjusted leverage is not within the appropriate range"),
        40797: (False, "Exceeded the maximum settable leverage"),
        40798: (False, "Insufficient contract account balance"),
        40799: (False, "Cannot be less than the minimum transfer amount"),
        40800: (False, "Insufficient amount of margin"),
        40801: (False, "Cannot exceed the maximum transferable deposit amount"),
        40802: (False, "Position is zero and direct margin call is not allowed"),
        40803: (False, "The leverage is reduced and the amount of margin call is incorrect"),
        40804: (False, "The number of closed positions cannot exceed the number of positions held"),
        40805: (False, "Unsupported operation"),
        40806: (False, "Unsupported currency"),
        40807: (False, "The account does not exist"),
        40808: (False, "Parameter verification exception {0}"),
        40809: (False, "Execution price parameter verification exception"),
        40810: (False, "Triggered price parameter verification exception"),
        40811: (False, "The parameter {0} should not be null"),
        40812: (False, "The condition {0} is not met"),
        40813: (False, "The parameter {0} must have a value and cannot be empty"),
        40814: (False, "No change in leverage"),
        40815: (False, "The order price is higher than the highest bid price"),
        40816: (False, "The order price is lower than the lowest selling price"),
        40817: (False, "The current order status cannot be cancelled"),
        40818: (False, "The current order type cannot be cancelled"),
        40819: (False, "The order does not exist!"),
        40820: (False, "The order price for closing a long position is not allowed to be lower than the liquidation price"),
        40821: (False, "The closing order price cannot be higher than the liquidation price"),
        40822: (False, "The contract configuration does not exist"),
        40823: (False, "The transaction or reasonable marked price does not exist"),
        40824: (False, "Currently, it is not allowed to list market orders"),
        40825: (False, "Contract opponent depth does not exist"),
        40826: (True, "Due to excessive price fluctuations, the market order cost is insufficient, and the position opening order failed."),
        40827: (False, "The bonus is not allowed to hold two-way positions"),
        40828: (False, "Special market making accounts cannot manually place orders"),
        40829: (False, "The take profit price of a long position should be greater than the average open price"),
        40830: (False, "The take profit price of the long position should be greater than the current price"),
        40831: (False, "The short position take profit price should be less than the average open price"),
        40832: (False, "The take profit price of short positions should be less than the current price"),
        40833: (False, "The stop loss price of a long position should be less than the average opening price"),
        40834: (False, "The stop loss price of the long position should be less than the current price"),
        40835: (False, "The stop loss price of the short position should be greater than the average opening price"),
        40836: (False, "The stop loss price of the short position should be greater than the current price"),
        40837: (False, "There is no position in this position, so stop-profit and stop-loss orders cannot be made"),
        40838: (False, "There is no position in this position, and automatic margin call cannot be set"),
        40839: (False, "The automatic margin call function of this contract has been suspended"),
        40840: (False, "Duplicate shard market making account"),
        40841: (False, "Online environment does not allow execution"),
        40842: (False, "Current configuration does not allow adjustment, please try again later"),
        40843: (False, "No data source key exists"),
        40844: (False, "This contract is under temporary maintenance"),
        40845: (False, "This contract has been removed"),
        40846: (False, "Status verification abnormal"),
        40847: (False, "The operation cannot be performed"),
        40848: (False, "Cannot open a copy transaction if there is a position"),
        40849: (False, "This user already has an ongoing copy"),
        40850: (False, "The copy is in progress, the balance cannot be transferred"),
        40851: (False, "Account status is wrong, cannot end copying"),
        40852: (False, "There are unfilled orders, cannot end the copy"),
        40853: (False, "There is an unexecuted plan order, cannot end the copy"),
        40854: (False, "This product does not support copy trading"),
        40855: (False, "The user has ended copying and cannot end copying again"),
        40856: (False, "Data abnormal"),
        40857: (False, "Document number error"),
        40858: (False, "Error tracking order status"),
        40859: (False, "This order is being closed and cannot be closed again"),
        40860: (False, "The trader does not exist and cannot be set to follow"),
        40861: (False, "The trader has been disabled and cannot be set to follow"),
        40862: (False, "Please cancel the current order"),
        40863: (False, "Please cancel the current plan"),
        40864: (False, "Please close the current position with orders"),
        40865: (False, "This order is being commissioned, and it is not currently supported to close the position"),
        40866: (False, "You are currently a trader, please close the position under the current order"),
        40867: (False, "Currently the maximum number of positions that can be closed is {0}, please go to the current order to close the position if the amount exceeds"),
        40868: (False, "You are currently a trader and currently do not support liquidation through planned orders"),
        40869: (False, "You are currently a trader and currently do not support modification of leverage"),
        40870: (False, "You are currently copying an order and currently do not support modifying the leverage"),
        40871: (False, "The leverage does not meet the configuration, and you cannot become a trader"),
        40872: (False, "Failed to adjust position, currently holding position or order or plan order"),
        40873: (False, "The account has a margin and needs to be transferred out"),
        40874: (False, "Whole position mode does not support automatic margin call"),
        40875: (False, "Whole position mode does not support margin adjustment"),
        40876: (False, "Too many tracking orders"),
        40877: (False, "Too many follow-up orders"),
        40878: (True, "The contract index data is abnormal. In order to avoid causing your loss, please try again later."),
        40879: (False, "The risk is being processed, and the funds cannot be adjusted."),
        40880: (False, "The risk is being processed and the leverage cannot be adjusted."),
        40881: (False, "There is currently an order, or an order is planned, and the leverage cannot be adjusted."),
        40882: (False, "You are currently a trader and you cannot switch to the full position mode"),
        40883: (False, "When the currencies are mixed, it cannot be adjusted to the warehouse-by-warehouse mode"),
        40884: (False, "When a one-way position is held, it cannot be adjusted to a position-by-position mode"),
        40885: (False, "In the case of position by position mode, it cannot be adjusted to one-way position"),
        40886: (False, "The automatic margin call cannot be adjusted in the full position mode"),
        40887: (False, "Failed to place the order, the number of single lightning open positions is at most {0}"),
        40888: (False, "Failed to place the order, the maximum amount of single lightning closing is {0}"),
        40889: (False, "The plan order of this contract has reached the upper limit"),
        40890: (False, "The order of stop-profit and stop-loss for this contract has reached the upper limit"),
        40891: (False, "Insufficient position, cannot set take profit or stop loss"),
        40892: (False, "Failed to place the order, the minimum number of positions opened by the trader is {0}"),
        40893: (False, "Unable to update the leverage factor of this position, there is not enough margin!"),
        40894: (False, "The documentary closing has been processed"),
        40895: (False, "The preset price does not match the order/execution price"),
        40896: (False, "The default stop profit and stop loss has been partially fulfilled and cannot be modified"),
        40897: (False, "The system experience gold account does not exist"),
        40898: (False, "The system experience gold account balance is insufficient"),
        40899: (False, "The number of stored users exceeds the limit"),
        40900: (False, "The system experience gold account is inconsistent"),
        40901: (False, "The contract experience fund balance is insufficient"),
        40902: (False, "Future time is not allowed"),
        40903: (False, "Failed to obtain leverage information"),
        40904: (False, "Failed to collect funds"),
        40905: (False, "Failed to collect user funds"),
        40906: (False, "Failed to pay user funds"),
        40907: (False, "The payment cannot be transferred"),
        40908: (False, "Concurrent operation failed"),
        40909: (False, "Transfer processing"),
        40910: (False, "Operation timed out"),
        40911: (False, "Request timestamp expired"),
        40912: (False, "Single cancel cannot exceed 50"),
        40913: (False, "{0} must be passed one"),
        40914: (False, "Trader the maximum leverage can use is {0}"),
        40915: (False, "Long position take profit price please > mark price"),
        40916: (False, "The business of this account has been restricted"),
        40917: (False, "Stop price for long positions please < mark price {0}"),
        40918: (False, "Traders open positions with orders too frequently"),
        40919: (False, "This function is not open yet"),
        40920: (False, "Position or order exists, the position mode cannot be switched"),
        40921: (False, "The order size cannot exceed the maximum size of the positionLevel"),
        40922: (False, "Only work order modifications are allowed"),
        40923: (False, "Order size and price have not changed"),
        40924: (False, "orderId and clientOid must have one"),
        40925: (False, "Price or size must be passed in together"),
        40927: (False, "The return field type or dest of this order does not meet expectations"),
        40928: (False, "Risk control, currently your max open size is {0} {1}. The size was calculated with all the main-sub accounts"),
        40929: (False, "TraderPro Maximum leverage is {0}X"),
        40930: (False, "The remaining quantity for your normal order is {0}{1}, and the quantity for post only order is {2}{3}"),
        40931: (False, "Trigger the risk control of position closing, prohibiting position closing"),
        40932: (False, "Risk control, you can currently open a maximum position of {0} {1}. The risk control proportion limit for a uid is calculated including all main accounts and sub-accounts."),
        43071: (False, "Trigger order limit for a single trading pair is {0}"),
        43075: (False, "Position pattern mismatch"),
        41104: (False, "Unsupported coin: {0}"),
        43129: (False, "Transfer coin not supported or invalid coin"),
        43130: (False, "StartTime params error"),
        41001: (False, "The account does not exist"),
        41002: (False, "Param error {0}"),
        49050: (False, "Unsupported chain"),
        49051: (False, "Missing callback signature request header"),
        49052: (False, "Callback signature verification failed"),
        49053: (False, "Cannot bind other platforms"),
        49060: (False, "The switch of adding money to Cobo is not turned on"),
        49061: (False, "The custody currency is not allowed"),
        49062: (False, "FundId is invalid or does not exist {0}"),
        49063: (False, "The custody currency already exists"),
        49064: (False, "Insufficient amount of shadow account"),
        49065: (False, "User withdrawal address already exists"),
        49066: (False, "The switch of Cobo money reduction is not turned on"),
        49067: (False, "FundSupplementId is invalid {0}"),
        49068: (False, "No currency available for settlement"),
        49069: (False, "There is an unfinished fund process, cannot be cleared and settled"),
        49070: (False, "Clearing settlement must include all currencies"),
        49071: (False, "FundSettlementId is invalid {0}"),
        49072: (False, "Failed to get user assets"),
        49073: (False, "Confirm that the set of FundIds receivable for clearing and settlement is not all fundIds"),
        49074: (False, "The settlement process has not been completed, and fund operations cannot be performed"),
        49075: (False, "Failed to query the address list of bg clearing and settlement account"),
        49076: (False, "Cobo callback params error"),
        49077: (False, "Failed to call the Cobo transaction query interface"),
        49078: (False, "Cobo withdrawal transaction callback requestId is invalid {0}"),
        49079: (False, "Supplement type illegal"),
        49080: (False, "Cobo confirms settlement, txId is invalid"),
        49081: (False, "Request amount parameter error"),
        70020: (False, "Account does not exist"),
        31057: (False, "User has not followed order"),
        22011: (False, "It is not allowed to set auto add margin in cross mode"),
        22012: (False, "Different business lines, {0} does not belong to {1} product"),
        22013: (False, "Abnormal status of position experience coupon"),
        22014: (False, "This position experience coupon does not exist"),
        22015: (False, "This user has no position experience coupon sub-account"),
        22016: (False, "This user is not a sub-account for position experience coupons and cannot operate experience coupons"),
        22017: (False, "The position experience coupon does not support this tokenId"),
        22018: (False, "The face value of the position experience coupon is a negative number"),
        22019: (False, "The position experience coupon has not expired yet"),
        22020: (False, "The leverage multiple is the leverage multiple of the current position and cannot be adjusted"),
        22021: (False, "Limit orders are not supported when placing orders with position experience coupons"),
        22022: (False, "The position experience coupon has been used"),
        22023: (False, "The trial coupon for this position has expired"),
        22024: (False, "The experience coupon for this position has been recycled"),
        22025: (False, "Margin cannot be added to the experience coupon account"),
        22026: (False, "The position mode cannot be adjusted for the experience coupon account"),
        22027: (False, "The position experience coupon does not support this currency pair"),
        22028: (False, "The position experience coupon does not support this type of order"),
        40104: (False, "Based on your IP address, it appears that you are located in a country or region where we are currently unable to provide services"),
        70006: (False, "Parameter value range verification failed: 0"),
        70007: (False, "Parameter verification failed: {0}, please make sure the time is within 30 days"),
        70008: (False, "Parameter verification failed: {0}, please make sure the time is within 30 days"),
        80001: (False, "Illegal params"),
        80002: (True, "System error"),
        80003: (False, "Loan coin not exist"),
        80004: (False, "Place coin not exist"),
        80005: (False, "Place single minimum limit"),
        80006: (False, "Place single maximum limit"),
        80007: (False, "Loan single minimum limit"),
        80008: (False, "Loan single maximum limit"),
        80009: (False, "Loan pool not enough"),
        80010: (False, "Place float exceed"),
        80011: (False, "Order does not exist"),
        80012: (False, "Pledge does not exist"),
        80013: (False, "Extract exceed maximum limit"),
        80014: (False, "Operate limit amount is {0} USDT"),
        80015: (False, "Order count maximum limit"),
        80016: (False, "Order status illegal"),
        59001: (False, "Product does not exist"),
        59002: (False, "Insufficient product balance"),
        59003: (False, "This product is not available for purchase yet"),
        59004: (False, "You are not a VIP and cannot purchase this product"),
        59005: (False, "KYC verification not performed"),
        59006: (False, "The country where KYC is located cannot apply for subscription"),
        59007: (False, "Minimum limit for single currency subscription"),
        59008: (False, "Maximum single currency subscription limit"),
        59009: (False, "The subscription amount does not meet the step size verification"),
        59010: (False, "The precision of the subscription amount cannot exceed {0} digits"),
        59011: (False, "Insufficient balance"),
        59012: (False, "Product does not exist"),
        59013: (False, "Parameter exception: {0}"),
        59014: (False, "Parameter precision exception"),
        59015: (False, "The product is not online and cannot be purchased"),
        59016: (False, "The total position of a single person is exceeded"),
        59017: (False, "Product subscription has been suspended"),
        59018: (False, "The subscription start time has not been reached"),
        59019: (False, "The subscription time range is {0} ~ {1}"),
        59020: (False, "Minimum limit for single subscription"),
        59021: (False, "Operation failed"),
        59022: (False, "Insufficient balance"),
        59023: (False, "Insufficient product remaining quota, remaining {0}"),
        59024: (False, "Amount cannot be empty when redeeming current financial management"),
        59025: (False, "OrderId cannot be empty when redeeming regular financial management"),
        59026: (False, "Product does not exist"),
        59027: (False, "This product is a novice product. You are not a novice user. Please choose another product"),
        59028: (False, "Product hidden"),
        59029: (False, "Product cannot be subscribed"),
        59030: (False, "Exceeding the max amount for one subscription"),
        59031: (False, "Cannot perform redemption operation"),
        59033: (False, "Less than redemption minimum limit"),
        59034: (False, "The redemption amount accuracy cannot exceed {0} digits"),
        59035: (False, "The redemption amount must be greater than the minimum limit"),
        59036: (False, "Exceeded maximum single transaction limit"),
        59037: (False, "The current order status does not allow operation"),
        59038: (False, "Redemption is not allowed on the day of expiration"),
        59039: (False, "Cannot perform redemption operation"),
        59040: (False, "The redemption time range is {0}-{1}"),
        59041: (False, "The accuracy of the subscription amount is not met"),
        59042: (False, "Insufficient balance"),
        59043: (False, "Insufficient product remaining quota, remaining {0}"),

        # Continue adding the rest of the error codes in the same format...

    }

    def __init__(self, api_key: str, api_secret: str, api_passphrase: str = "") -> None:
        super().__init__(api_key, api_secret)
        
        self.passphrase = api_passphrase
        self.base_headers = {
            "ACCESS-KEY": self.api_key,
            "ACCESS-SIGN": None,
            "ACCESS-PASSPHRASE": self.passphrase,
            "ACCESS-TIMESTAMP": self.timestamp,
            "locale": "en-US",
            "Content-Type": "application/json",
        }

    def sign(self, method:str, baseUrl: str, requestPath: str, _format:dict):
        
        full_request_path = baseUrl + requestPath + self.params_to_str(_format["params"])
        
        reqBody = orjson.dumps(_format["body"]).decode() if method == "POST" else ""
            
        to_sign_string = str(self.update_timestamp()) + method.upper() + full_request_path + reqBody
        
        hash_signature = hmac.new(
            key=self.api_secret.encode(),
            msg=orjson.dumps(to_sign_string),
            digestmod=hashlib.sha256,
        )
        self.base_headers["ACCESS-TIMESTAMP"] = self.timestamp #signature timestamp and header timestamp need to be the same
        signature = str(base64.b64encode(hash_signature.digest()), 'utf8')
        return signature

    def params_to_str(params: dict):
        
        query_parameters = "?"
        for key_val_pair in params:
            query_parameters += str(key_val_pair[0]) + "=" + str(key_val_pair[1]) + "&"
        
        return query_parameters[0:-1] #Will remove the lase "&" sign and will also return empty if no params and string is only "?"

    def error_handler(self, recv):
        error_code = int(recv.get("code", 0))
        return self.errors.get(
            error_code,
            (False, f"Unknown error code: {error_code}")
        )
        