---
# "Binance", "Bybit", "Hyperliquid", ...
exchanges:
  Binance:
    symbol: BTCUSDT
    type: data
  Hyperliquid:
    symbol: BTC
    type: trading
  #bitget:
    #symbol: SBTCUSDT
    #type: trading

# "plain", "stink" ,...
quote_generator: sandbox

# The params "total_orders" and "max_position" must be present in any
# new strategies created! Max position is auto converted to quote
# units so always keep this value in $ (USD).
parameters:
  plain:
    total_orders: 10            # Consider your rate limits!
    max_position: 100           # Value in $ (USD)
    minimum_spread: 10          # Value in BPS (Basis Points)
    aggressiveness: 0.75        # Must be 0.0 <-> 1.0

  stink:
    total_orders: 10            # Consider your rate limits!
    max_position: 100           # Value in $ (USD)
    minimum_spread: 50          # Value in BPS (Basis Points)
    maximum_spread: 250         # Value in BPS (Basis Points)
  
  sandbox:
    total_orders: 2             # Consider your rate limits!
    max_position: 50            # Value in $ (USD)
    minimum_spread: 15          # Value in BPS (Basis Points)
    maximum_spread: 250         # Value in BPS (Basis Points)
    take_profit: 10             #Value to place take profit from avg entry (Basis Points)
    generation_interval: 1000   #Interval to generate new quotes in ms
    liquidation_timer: 30000    #Max time interval before purging position with market order (ms)
...
